#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -sf $DOTFILES/zsh/.zshrc $HOME/.zshrc

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

ln -sf $DOTFILES/git/.gitconfig $HOME/.gitconfig

ln -sf $DOTFILES/git/.gitignore $HOME/.gitignore
